#!/bin/sh

clipdel -d ".*"
clipmenud &
playerctld daemon &
feh --bg-fill Pictures/wallpapers/6bmj4y4wgfy01.jpg --no-fehbg
redshift -l 56:10 &
pcmanfm -d &
nm-applet &
exec i3 & wmpid=$!

sleep 5
source $HOME/.config/i3/after &
wait $wmpid
