#!/bin/sh

clipdel -d ".*"
clipmenud &
playerctld daemon &
feh --bg-scale Pictures/wallpapers/space.png --no-fehbg --no-xinerama
redshift -l 56:10 &
pcmanfm -d &
nm-applet &
exec i3 & wmpid=$!

sleep 5
source $HOME/.config/i3/after
wait $wmpid
