#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

~/.local/bin/clipclear &
clipmenud &
playerctld daemon &
redshift -l 55.7:12.6 -t 5700:4000 -g 0.9 -m randr -v &
unclutter -b &
nextcloud --background &
xwallpaper --center $XDG_CONFIG_HOME/wallpaper/bg &
betterlockscreen -u $XDG_CONFIG_HOME/wallpaper/lock &
~/.local/bin/comptoggle &
~/.local/bin/rate &
~/.local/bin/screensaver &
sxhkd &
exec i3
